# Generated by Django 6.0.7 on 2026-07-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(blank=True, help_text='e.g. Garden Side', max_length=40)),
                ('seats', models.PositiveSmallIntegerField(default=4)),
                ('shape', models.CharField(choices=[('SQUARE', 'Square'), ('ROUND', 'Round'), ('RECT', 'Rectangle')], default='SQUARE', max_length=6)),
                ('pos_x', models.PositiveSmallIntegerField(default=0)),
                ('pos_y', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('BILLED', 'Billed')], default='AVAILABLE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'restaurant_tables',
                'ordering': ['pos_y', 'pos_x', 'number'],
            },
        ),
    ]
