# Generated by Django 6.0.3 on 2026-07-28 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_bill_customer_bill_net_payable_bill_points_earned_and_more'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(blank=True, max_length=40)),
                ('waba_id', models.CharField(blank=True, max_length=40, verbose_name='WABA ID')),
                ('access_token', models.TextField(blank=True)),
                ('app_id', models.CharField(blank=True, max_length=40)),
                ('app_secret', models.CharField(blank=True, max_length=80)),
                ('verify_token', models.CharField(blank=True, help_text='Owner khud set karega — Meta pe wahi daalna hai', max_length=60)),
                ('is_live', models.BooleanField(default=False)),
                ('send_welcome', models.BooleanField(default=True)),
                ('send_bill_receipt', models.BooleanField(default=True)),
                ('send_feedback_request', models.BooleanField(default=True)),
                ('send_winback', models.BooleanField(default=True)),
                ('send_birthday', models.BooleanField(default=True)),
                ('send_anniversary', models.BooleanField(default=True)),
                ('winback_days', models.PositiveIntegerField(default=30, help_text='Itne din na aane par win-back message jayega')),
                ('regular_min_visits', models.PositiveIntegerField(default=2, help_text='Itni visits ke baad customer "Regular" mana jayega')),
                ('public_base_url', models.CharField(default='http://localhost:3000', help_text='Feedback link isi URL se banega', max_length=200)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp config',
                'verbose_name_plural': 'WhatsApp config',
                'db_table': 'whatsapp_config',
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_request', to='billing.bill')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='customers.customer')),
            ],
            options={
                'db_table': 'feedback_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('language', models.CharField(default='hi', max_length=10)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused')], default='PENDING', max_length=10)),
                ('header_text', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True, help_text='{{1}}, {{2}} … placeholders')),
                ('footer_text', models.TextField(blank=True)),
                ('variable_count', models.PositiveSmallIntegerField(default=0)),
                ('meta_id', models.CharField(blank=True, max_length=60)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'whatsapp_templates',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'language'), name='uniq_template_name_lang')],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('segment', models.CharField(choices=[('ALL', 'Sab customers'), ('NEW', 'New — pehli baar aaye'), ('REGULAR', 'Regular — baar baar aate hain'), ('INACTIVE', 'Inactive — kaafi din se nahi aaye')], default='ALL', max_length=10)),
                ('body', models.TextField(help_text='Hindi message — {name} customer ke naam se badal jayega')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Bheja ja chuka')], default='DRAFT', max_length=6)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.messagetemplate')),
            ],
            options={
                'db_table': 'whatsapp_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriggerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('WELCOME', 'Welcome — naya customer'), ('BILL_RECEIPT', 'Bill receipt — checkout ke baad'), ('FEEDBACK', 'Feedback — 1-5 star link'), ('WINBACK', 'Win-back — kaafi din se nahi aaye'), ('BIRTHDAY', 'Birthday offer'), ('ANNIVERSARY', 'Anniversary offer'), ('BROADCAST', 'Broadcast campaign')], max_length=20, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindings', to='whatsapp.messagetemplate')),
            ],
            options={
                'db_table': 'whatsapp_trigger_bindings',
                'ordering': ['trigger'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('direction', models.CharField(choices=[('OUT', 'Bheja'), ('IN', 'Aaya')], max_length=3)),
                ('trigger', models.CharField(blank=True, choices=[('WELCOME', 'Welcome — naya customer'), ('BILL_RECEIPT', 'Bill receipt — checkout ke baad'), ('FEEDBACK', 'Feedback — 1-5 star link'), ('WINBACK', 'Win-back — kaafi din se nahi aaye'), ('BIRTHDAY', 'Birthday offer'), ('ANNIVERSARY', 'Anniversary offer'), ('BROADCAST', 'Broadcast campaign')], max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('RECEIVED', 'Received')], default='QUEUED', max_length=10)),
                ('is_mock', models.BooleanField(default=True)),
                ('wa_message_id', models.CharField(blank=True, max_length=80)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='billing.bill')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.campaign')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='customers.customer')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.messagetemplate')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='whatsapp_me_phone_ad7a2d_idx')],
            },
        ),
    ]
