# Generated by Django 6.0.3 on 2026-08-04 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCampaignRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('trigger_event', models.CharField(choices=[('DAYS_SINCE_LAST_VISIT', 'Days since last visit')], default='DAYS_SINCE_LAST_VISIT', max_length=50)),
                ('target_days', models.PositiveIntegerField(help_text='How many days after the event to trigger.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.messagetemplate')),
            ],
            options={
                'db_table': 'whatsapp_auto_campaign_rules',
                'ordering': ['trigger_event', 'target_days'],
            },
        ),
        migrations.CreateModel(
            name='AutoCampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_campaign_logs', to='customers.customer')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.whatsappmessage')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='whatsapp.autocampaignrule')),
            ],
            options={
                'db_table': 'whatsapp_auto_campaign_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['customer', 'rule', '-sent_at'], name='whatsapp_au_custome_37de34_idx')],
            },
        ),
    ]
