# Generated by Django 6.0.7 on 2026-08-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_autocampaignrule_autocampaignlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='body',
            field=models.TextField(blank=True, help_text='Hindi message — {name} customer ke naam se badal jayega'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHED', 'Scheduled'), ('SENT', 'Bheja ja chuka')], default='DRAFT', max_length=6),
        ),
    ]
