# Generated by Django 6.0.7 on 2026-08-09 09:57

from django.db import migrations

def populate_custom_roles(apps, schema_editor):
    CustomRole = apps.get_model('auth_app', 'CustomRole')
    User = apps.get_model('auth_app', 'User')

    # Define base permissions
    owner_perms = {
        'view_dashboard': True,
        'view_pos': True,
        'view_floor_map': True,
        'view_kot': True,
        'view_menu': True,
        'view_customers': True,
        'view_orders': True,
        'view_whatsapp': True,
        'view_coupons': True,
        'view_reports': True,
        'view_settings': True,
        'punch_order': True,
        'print_kot': True,
        'print_bill': True,
        'settle_bill': True,
        'cancel_bill': True,
        'manage_users': True,
        'owner_override': True,
        'manage_roles': True,
    }

    cashier_perms = {
        'view_dashboard': True,
        'view_pos': True,
        'view_floor_map': True,
        'view_kot': True,
        'view_menu': True,
        'view_customers': True,
        'view_orders': True,
        'punch_order': True,
        'print_kot': True,
        'print_bill': True,
        'settle_bill': True,
        'cancel_bill': True,  # Cashiers can cancel unpaid bills
    }

    waiter_perms = {
        'view_dashboard': True,
        'view_pos': True,
        'view_floor_map': True,
        'view_kot': True,
        'punch_order': True,
        'print_kot': True,
        'print_bill': True,
        'settle_bill': False, # Waiters cannot settle
    }

    owner_role, _ = CustomRole.objects.get_or_create(
        name='Owner',
        defaults={'permissions': owner_perms, 'is_system': True}
    )
    cashier_role, _ = CustomRole.objects.get_or_create(
        name='Cashier',
        defaults={'permissions': cashier_perms, 'is_system': True}
    )
    waiter_role, _ = CustomRole.objects.get_or_create(
        name='Waiter',
        defaults={'permissions': waiter_perms, 'is_system': True}
    )

    for user in User.objects.all():
        if user.role == 'OWNER':
            user.custom_role = owner_role
        elif user.role == 'CASHIER':
            user.custom_role = cashier_role
        elif user.role == 'WAITER':
            user.custom_role = waiter_role
        else:
            user.custom_role = cashier_role # Default fallback
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customrole_user_custom_role'),
    ]

    operations = [
        migrations.RunPython(populate_custom_roles, reverse_code=migrations.RunPython.noop),
    ]
