# Generated by Django 6.0.7 on 2026-09-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20260809_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrole',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
