# Generated by Django 6.0.7 on 2026-07-28 03:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='ReBill Restaurant', max_length=120)),
                ('address', models.TextField(default='123, Main Market, New Delhi - 110001')),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('bill_prefix', models.CharField(default='RB', max_length=8)),
                ('bill_number_padding', models.PositiveSmallIntegerField(default=4)),
                ('next_bill_number', models.PositiveIntegerField(default=1)),
                ('next_kot_number', models.PositiveIntegerField(default=1)),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Isse zyada discount dene par Owner password maanga jaayega', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'restaurant settings',
                'db_table': 'restaurant_settings',
            },
        ),
    ]
