# Generated by Django 6.0.7 on 2026-07-28 04:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='loyalty_earn_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Itne rupaye kharch karne par', max_digits=8),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='loyalty_earn_points',
            field=models.PositiveIntegerField(default=1, help_text='Itne points milenge'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='loyalty_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='loyalty_max_redeem_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Ek bill me zyada se zyada itne % tak points se bhar sakte hain', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='loyalty_min_redeem_points',
            field=models.PositiveIntegerField(default=50, help_text='Isse kam points redeem nahi ho sakte'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='loyalty_redeem_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='1 point = itne rupaye', max_digits=6),
        ),
    ]
