# Generated by Django 6.0.7 on 2026-08-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_restaurantsettings_loyalty_earn_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='ai_connection_token',
            field=models.CharField(blank=True, help_text='Secure token for AI Gateway connections. Keep this secret.', max_length=64, null=True, unique=True),
        ),
    ]
