# Generated by Django 6.0.3 on 2026-08-24 18:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_restaurantsettings_ai_connection_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='city',
            field=models.CharField(default='New Delhi', help_text='City for local weather & holidays', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('28.613900'), help_text='Latitude for weather API', max_digits=9),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('77.209000'), help_text='Longitude for weather API', max_digits=9),
        ),
    ]
