# Generated by Django 6.0.7 on 2026-10-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_restaurantsettings_city_restaurantsettings_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='customer_details_mandatory',
            field=models.BooleanField(default=False, help_text='Dine-in aur Takeaway dono bills me customer name aur phone number capture karna mandatory hai ya nahi'),
        ),
    ]
