# Generated by Django on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_order_one_open_order_per_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tag_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(
                blank=True,
                choices=[
                    ('CASH', 'Cash'),
                    ('CARD', 'Card'),
                    ('UPI', 'UPI'),
                    ('DUE', 'Credit / Udhar'),
                    ('SPLIT', 'Split Payment'),
                    ('ONLINE', 'Online'),
                ],
                max_length=10,
            ),
        ),
    ]
