# Generated by Django 6.0.7 on 2026-07-28 03:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'menu_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('food_type', models.CharField(choices=[('VEG', 'Veg'), ('NON_VEG', 'Non-Veg')], default='VEG', max_length=8)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_available', models.BooleanField(default=True, help_text='Out of stock ke liye off karo')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='menu.category')),
            ],
            options={
                'db_table': 'menu_items',
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.CharField(choices=[('HALF', 'Half'), ('FULL', 'Full')], default='FULL', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.menuitem')),
            ],
            options={
                'db_table': 'menu_item_variants',
                'ordering': ['item', '-portion'],
            },
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_item_name_per_category'),
        ),
        migrations.AddConstraint(
            model_name='menuitemvariant',
            constraint=models.UniqueConstraint(fields=('item', 'portion'), name='uniq_portion_per_item'),
        ),
    ]
