import { useState } from 'react'
import { errorMessage } from '@/services/api'
import { bills as billApi } from '@/services/billing'
import { money } from '@/utils/format'
import Button from '@/components/ui/Button'
import { Input } from '@/components/ui/Field'
import Modal from '@/components/ui/Modal'

const QUICK_REASONS = [
  'Bill generated by mistake',
  'Customer cancelled order',
  'Wrong item charged',
  'Food quality issue',
]

/**
 * Cancel / refund a bill.
 */
export default function CancelBillModal({ bill, isOwner, onClose, onCancelled }) {
  const [reason, setReason] = useState('')
  const [username, setUsername] = useState('owner')
  const [password, setPassword] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')

  const isRefund = bill.status === 'PAID'
  const needsOwner = isRefund && !isOwner
  const due = Number(bill.redeem_amount) > 0 ? bill.net_payable : bill.total

  const submit = async (event) => {
    event.preventDefault()
    setBusy(true)
    setError('')
    try {
      const payload = { reason: reason.trim() }
      if (needsOwner) {
        payload.owner_username = username.trim()
        payload.owner_password = password
      }
      onCancelled(await billApi.cancel(bill.id, payload))
    } catch (err) {
      setError(errorMessage(err, 'Failed to cancel bill.'))
    } finally {
      setBusy(false)
    }
  }

  return (
    <Modal
      open
      size="sm"
      onClose={onClose}
      title={isRefund ? 'Refund Bill' : 'Cancel Bill'}
      subtitle={`${bill.bill_number} · ${money(due)}`}
      footer={
        <>
          <Button variant="secondary" onClick={onClose} disabled={busy}>
            Cancel
          </Button>
          <Button
            form="cancel-bill"
            type="submit"
            variant="danger"
            loading={busy}
            disabled={reason.trim().length < 4 || (needsOwner && !password)}
          >
            {isRefund ? 'Process Refund' : 'Confirm Cancellation'}
          </Button>
        </>
      }
    >
      <form id="cancel-bill" onSubmit={submit} className="space-y-4">
        <div className="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2.5 text-sm text-rose-900">
          {isRefund ? (
            <>
              This bill is already paid. Cancelling it will reverse customer loyalty points and update visit history.
            </>
          ) : (
            <>Bill will be cancelled and table marked available.</>
          )}
        </div>

        <div>
          <label htmlFor="reason" className="mb-1.5 block text-sm font-medium text-slate-700">
            Reason <span className="text-rose-500">*</span>
          </label>
          <Input
            id="reason"
            autoFocus
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            placeholder="Reason for cancellation"
          />
          <div className="mt-2 flex flex-wrap gap-1.5">
            {QUICK_REASONS.map((r) => (
              <button
                key={r}
                type="button"
                onClick={() => setReason(r)}
                className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600 transition hover:bg-slate-200"
              >
                {r}
              </button>
            ))}
          </div>
        </div>

        {needsOwner && (
          <div className="space-y-3 rounded-lg border border-amber-200 bg-amber-50 p-3">
            <p className="text-sm font-medium text-amber-900">
              Owner credentials required to refund a paid bill
            </p>
            <Input
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="Owner username"
              autoComplete="off"
            />
            <Input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Owner password"
              autoComplete="off"
            />
          </div>
        )}

        {error && (
          <p
            role="alert"
            className="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700"
          >
            {error}
          </p>
        )}
      </form>
    </Modal>
  )
}
