from django.urls import path
from .views import (
    AIRootDirectoryView,
    AISalesSummaryView,
    AIDailyReportView,
    AITopProductsView,
    AITopCustomersView,
    AITextReportView,
    AISchemaView,
    AIRunQueryView,
    AIContextDailyView,
    AIDemandForecastView,
    # ── Safe CRUD views ──
    AICancelBillView,
    AIToggleMenuItemView,
    AIUpdateMenuPriceView,
    AIUpdateCustomerView,
    # ── Floor Map & Table Management views ──
    AIGetAllTablesView,
    AIGetTableDetailView,
    AIUpdateTableStatusView,
    AICreateTableView,
    AIUpdateTableView,
    AIDeleteTableView,
    AIRearrangeTablesView,
    AIBulkCreateTablesView,
    AITransferTableOrderView,
    AIAddItemToOrderView,
    AIRemoveItemFromOrderView,
    AIGetOpenOrdersView,
    AISettleOrderView,
    AIGetSettingsView,
    AIToggleMandatoryCustomerView,
)

urlpatterns = [
    path('', AIRootDirectoryView.as_view(), name='ai-root-directory'),
    path('schema/', AISchemaView.as_view(), name='ai-schema'),
    path('query/', AIRunQueryView.as_view(), name='ai-query'),
    path('sales/summary/', AISalesSummaryView.as_view(), name='ai-sales-summary'),
    path('sales/daily/', AIDailyReportView.as_view(), name='ai-sales-daily'),
    path('products/top/', AITopProductsView.as_view(), name='ai-top-products'),
    path('customers/top/', AITopCustomersView.as_view(), name='ai-top-customers'),
    path('text-report/', AITextReportView.as_view(), name='ai-text-report'),
    path('context/daily/', AIContextDailyView.as_view(), name='ai-context-daily'),
    path('forecast/demand/', AIDemandForecastView.as_view(), name='ai-forecast-demand'),
    # ── Safe CRUD endpoints ──
    path('bills/cancel/', AICancelBillView.as_view(), name='ai-cancel-bill'),
    path('menu/toggle/', AIToggleMenuItemView.as_view(), name='ai-toggle-menu-item'),
    path('menu/price/', AIUpdateMenuPriceView.as_view(), name='ai-update-menu-price'),
    path('customers/update/', AIUpdateCustomerView.as_view(), name='ai-update-customer'),
    # ── Floor Map & Table Management endpoints ──
    path('tables/', AIGetAllTablesView.as_view(), name='ai-get-all-tables'),
    path('tables/detail/', AIGetTableDetailView.as_view(), name='ai-get-table-detail'),
    path('tables/status/', AIUpdateTableStatusView.as_view(), name='ai-update-table-status'),
    path('tables/create/', AICreateTableView.as_view(), name='ai-create-table'),
    path('tables/update/', AIUpdateTableView.as_view(), name='ai-update-table'),
    path('tables/delete/', AIDeleteTableView.as_view(), name='ai-delete-table'),
    path('tables/layout/', AIRearrangeTablesView.as_view(), name='ai-rearrange-tables'),
    path('tables/bulk-create/', AIBulkCreateTablesView.as_view(), name='ai-bulk-create-tables'),
    path('tables/transfer/', AITransferTableOrderView.as_view(), name='ai-transfer-table-order'),
    path('tables/add-item/', AIAddItemToOrderView.as_view(), name='ai-add-item-to-order'),
    path('tables/remove-item/', AIRemoveItemFromOrderView.as_view(), name='ai-remove-item-from-order'),
    # ── Order & Bill Settlement endpoints ──
    path('orders/open/', AIGetOpenOrdersView.as_view(), name='ai-get-open-orders'),
    path('orders/settle/', AISettleOrderView.as_view(), name='ai-settle-order'),
    # ── Settings & Policy endpoints ──
    path('settings/', AIGetSettingsView.as_view(), name='ai-get-settings'),
    path('settings/mandatory-customer/', AIToggleMandatoryCustomerView.as_view(), name='ai-toggle-mandatory-customer'),
]
