# Generated by Django 6.0.3 on 2026-08-24 18:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFootfallContextLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Target date', unique=True)),
                ('weather_condition', models.CharField(default='Clear Sky', help_text='E.g. Sunny, Heavy Rain, Fog', max_length=80)),
                ('weather_code', models.IntegerField(default=0, help_text='WMO Weather Interpretation Code')),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, help_text='Max temperature in Celsius', max_digits=5, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, help_text='Min temperature in Celsius', max_digits=5, null=True)),
                ('temp_avg', models.DecimalField(blank=True, decimal_places=2, help_text='Average temperature in Celsius', max_digits=5, null=True)),
                ('precipitation_mm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rainfall in mm', max_digits=6)),
                ('rain_probability_percent', models.PositiveSmallIntegerField(default=0, help_text='Chance of rain (0-100%)')),
                ('humidity_percent', models.PositiveSmallIntegerField(default=50, help_text='Average humidity percentage')),
                ('is_holiday', models.BooleanField(default=False)),
                ('holiday_name', models.CharField(blank=True, default='', max_length=120)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_long_weekend', models.BooleanField(default=False)),
                ('is_event_day', models.BooleanField(default=False)),
                ('event_name', models.CharField(blank=True, default='', max_length=120)),
                ('event_category', models.CharField(blank=True, default='', help_text='Festival, Sports, National Holiday, etc.', max_length=50)),
                ('total_bills', models.PositiveIntegerField(default=0)),
                ('dine_in_bills', models.PositiveIntegerField(default=0)),
                ('takeaway_bills', models.PositiveIntegerField(default=0)),
                ('delivery_bills', models.PositiveIntegerField(default=0)),
                ('guest_count', models.PositiveIntegerField(default=0, help_text='Total pax/covers served')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('dine_in_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('delivery_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('peak_hour', models.PositiveSmallIntegerField(blank=True, help_text='Busiest hour of the day (0-23)', null=True)),
                ('top_selling_category', models.CharField(blank=True, default='', max_length=100)),
                ('top_selling_item', models.CharField(blank=True, default='', max_length=120)),
                ('snapshot_type', models.CharField(choices=[('ACTUAL', 'Actual Recorded Day'), ('FORECAST', 'Upcoming Forecast')], default='ACTUAL', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Footfall Context Log',
                'verbose_name_plural': 'Daily Footfall Context Logs',
                'db_table': 'daily_footfall_context_log',
                'ordering': ['-date'],
            },
        ),
    ]
